# Generated by Django 4.2 on 2025-04-19 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dogs', '0002_alter_breed_options_alter_dog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs_dogs', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
    ]
