# Generated by Django 4.2 on 2025-04-20 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0004_alter_dog_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='views_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество просмотров'),
        ),
    ]
