# Generated by Django 4.2 on 2025-04-23 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0005_dog_views_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedigree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=50, unique=True, verbose_name='Регистрационный номер')),
                ('issued_by', models.CharField(max_length=100, verbose_name='Кем выдана родословная')),
                ('issue_date', models.DateField(verbose_name='Дата выдачи')),
                ('dog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedigree', to='dogs.dog', verbose_name='Собака')),
                ('father', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_of', to='dogs.dog', verbose_name='Отец')),
                ('mother', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_of', to='dogs.dog', verbose_name='Мать')),
            ],
            options={
                'verbose_name': 'Родословная',
                'verbose_name_plural': 'Родословные',
            },
        ),
    ]
