# Generated by Django 4.2 on 2025-04-23 09:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dogs', '0006_pedigree'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='breed',
            options={},
        ),
        migrations.AlterModelOptions(
            name='dog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pedigree',
            options={},
        ),
        migrations.AlterField(
            model_name='breed',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dog',
            name='birth_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='dog',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to='dogs.breed'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dogs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dog',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='dogs/'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='views_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='dog',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pedigree', to='dogs.dog'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='father',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='father_of', to='dogs.dog'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='issue_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='issued_by',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mother_of', to='dogs.dog'),
        ),
        migrations.AlterField(
            model_name='pedigree',
            name='registration_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
