# Generated by Django 4.2 on 2025-04-25 02:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0008_alter_breed_options_alter_dog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
