# Generated by Django 4.2 on 2025-04-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0009_dog_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
