# Generated by Django 4.2 on 2025-04-25 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0010_dog_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='views',
            new_name='likes',
        ),
    ]
