# Generated by Django 4.2 on 2025-05-01 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0011_rename_views_dog_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='likes',
        ),
        migrations.AlterField(
            model_name='dog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
