# Generated by Django 4.2 on 2025-05-03 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0012_remove_dog_likes_alter_dog_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='created_at',
        ),
        migrations.AddField(
            model_name='dog',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
